# bot token
botToken: ""
# discord server id
serverId: ""
# discord server chat channel id
channelId: ""

# enable debug
debug: false

# enable bot status
# Playing _________
enableBotStatus: true
botStatus: "Minecraft"

# set text channel topic if it is empty
channelTopic: "Powered by DiscordChat for Nukkit"

# enable !playerlist command on discord
playerListCommand: true
# enable !ip command on discord
ipCommand: true
serverIp: "play.example.com"
serverPort: "19132"

# enable join messages to discord
joinMessages: true
# enable quit messages to discord
quitMessages: true
# enable death messages to discord
deathMessages: true
# enable server start messages to discord
startMessages: true
# enable server stop messages to discord
stopMessages: true

# discord messages to minecraft
enableDiscordToMinecraft: true
# minecraft messages to discord
enableMinecraftToDiscord: true

# enable if you see Â in messages
windowsHost: false

# enable anti spam
antiSpam: true