# bot token
botToken: ""
# discord server id
serverId: ""
# discord server chat channel id
channelId: ""

# enable debug
debug: false

# enable bot status
# Playing _________
enableBotStatus: true
botStatus: "Minecraft"

# enable !playerlist command on discord
playerListCommand: true
# enable !ip command on discord
ipCommand: true
serverIp: "play.example.com"
serverPort: "19132"

# enable join messages to discord
joinMessages: true
# enable quit messages to discord
quitMessages: true
# enable death messages to discord
deathMessages: true

# discord messages to minecraft
enableDiscordToMinecraft: true
# minecraft messages to discord
enableMinecraftToDiscord: true

# enable if you host your server on windows computer to prevent Â in messages
windowsHost: true